import type { Meta, StoryObj } from '@storybook/angular';

import { ReportFrameComponent } from './report-frame.component';

const meta: Meta<ReportFrameComponent> = {
  title: 'Reports',
  component: ReportFrameComponent,
  parameters: {
    layout: 'fullscreen',
  },
};

export default meta;

type Story = StoryObj<ReportFrameComponent>;

export const Coverage: Story = {
  args: {
    title: 'Coverage Report',
    description: 'Istanbul unit test coverage report generated by npm run test:coverage.',
    src: '/reports/coverage/index.html',
  },
};

export const Playwright: Story = {
  args: {
    title: 'Playwright Report',
    description: 'Playwright end-to-end test report generated by npm run e2e.',
    src: '/reports/playwright/index.html',
  },
};